version: "3.9"
services:
  web:
    build: .
    ports:
      - "8140:8000"
      - "8141:8001"
    volumes:
      - /root/nginx/certificates:/certificates
      - /root/FileSharingBE/uploads:/app/uploads
    restart: always